project_name: counter

before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
    - git push
    - git push --tags
builds:
  -
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/ondrejsika/{{ .ProjectName }}/version.Version=v{{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"
      - goos: linux
        goarch: arm
        goarm: "6"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

dockers:
    -
      goos: linux
      goarch: amd64
      image_templates:
        - "ondrejsika/{{ .ProjectName }}:{{ .Tag }}"
        - "ondrejsika/{{ .ProjectName }}"
        - "ghcr.io/ondrejsika/{{ .ProjectName }}:{{ .Tag }}"
        - "ghcr.io/ondrejsika/{{ .ProjectName }}"
      dockerfile: Dockerfile.goreleaser
      ids:
        - "counter"
      build_flag_templates:
        - "--platform=linux/amd64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/ondrejsika/{{ .ProjectName }}"
        - "--label=maintainer=Ondrej Sika <ondrej@ondrejsika.com>"
    - goos: linux
      goarch: arm64
      image_templates:
        - "ondrejsika/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
        - "ondrejsika/{{ .ProjectName }}:arm64v8"
        - "ghcr.io/ondrejsika/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
        - "ghcr.io/ondrejsika/{{ .ProjectName }}:arm64v8"
      dockerfile: Dockerfile.goreleaser.arm64v8
      ids:
        - "counter"
      build_flag_templates:
        - "--platform=linux/arm64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/ondrejsika/{{ .ProjectName }}"
        - "--label=maintainer=ondrejsika <ondrej@ondrejsika.com>"

changelog:
  filters:
    exclude:
      - '^VERSION'
      - '^chore'
