apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    {{- range $k, $v := .Values.ingressExtraAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  {{ if .Values.ingressClassName }}
  ingressClassName: {{ .Values.ingressClassName }}
  {{ end }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.host }}-tls
  rules:
    - host: {{ required " .Values.host is required" .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-counter
                port:
                  number: 80
